= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/Anxton[Anton XU]
- https://github.com/BSCT-Tormod[Thomas Demeyere]
- https://github.com/OryannMcCloud[Oryann Prochaska]
- https://github.com/L-Yvelin[Louis Yvelin]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:isabelle.clavel@univ-tlse2.fr[IC]

== Contexte général

Nous allons produire un site internet pour la société _Commerce de la rue_.
Cette entreprise est spécialisée dans la vente de composants informatiques.
Suite à la crise sanitaire son chiffre d'affaires a drastiquement baissé et est actuellement stagnante.
Afin de relancer son activité, _Commerce de la rue_ doit se moderniser grâce à l'usage d'un site de vente en ligne attractif.
Elle souhaite se démarquer de ses concurrents, leur site doit pouvoir s'adresser aussi bien aux entreprises qu'aux particuliers.
Leur site s'adresse néanmoins uniquement aux usagers présents sur le territoire français pour des raisons de facilité.

=== Affectation des rôles 

- Thomas Demeyere : SCRUM Master 
- Oryann Prochaska : Product Owner 
- Anton Xu : Développeur 
- Louis Yvelin : Développeur 

=== Dépôt initial

Ce dépôt initial a été créé pour que tous les groupes de 2ème année aient les mêmes informations de départ.

Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

- `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande `git add -f` pour forcer l'ajout d'un fichier Jar qui ne bougera plus, pour archive par exemple).
- `.github` => le répertoire qui contient des éléments de gestion de projet :
** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
*** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
** `ISSUE_TEMPLATE` => le repertoire qui contient quelques templates pour vos issues.
*** `us.yml` => Exemple de template pour les User Stories
*** `bug.yml` => Exemple de template pour les issues de bug report

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

== Réalisations 

Nous avons trié les compétences par dossier : 

- Le dossier _devweb_ contient toutes les pages HTML (avec le PHP inclu dedans), la page CSS ainsi que les images incluses.
- Le dossier _iot_ contient le fichier Python pour récuperer les données des capteurs et le fichier config.json dans lequel est inclu les listes utiles au programme.
- Le dossier _Documentation_ contient le fichier d'installation de l'application IOT.
- Le dossier _bd_ contient le fichier avec diagramme de classes, dico des données et schéma relationnel ainsi que le script de création de la base de données.

=== Installation


== Rendus hebdomadaire de Gestion de projet & Qualité

Après chaque sprint (semaine) une nouvelle version de notre application (release) sera disponible.
Nous utiliserons pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

Nous mettrons à jour le `README.adoc` avec les informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v2
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application
