= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/Anxton[Anton XU]
- https://github.com/BSCT-Tormod[Thomas Demeyere]
- https://github.com/OryannMcCloud[Oryann Prochaska]
- https://github.com/L-Yvelin[Louis Yvelin]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:isabelle.clavel@univ-tlse2.fr[IC]

== Contexte général

Nous allons produire un site internet pour la société _Commerce de la rue_.
Cette entreprise est spécialisée dans la vente de composants informatiques.
Suite à la crise sanitaire son chiffre d'affaires a drastiquement baissé et est actuellement stagnante.
Afin de relancer son activité, _Commerce de la rue_ doit se moderniser grâce à l'usage d'un site de vente en ligne attractif.
Elle souhaite se démarquer de ses concurrents, leur site doit pouvoir s'adresser aussi bien aux entreprises qu'aux particuliers.
Leur site s'adresse néanmoins uniquement aux usagers présents sur le territoire français pour des raisons de facilité.

=== Affectation des rôles 

- Thomas Demeyere : SCRUM Master 
- Oryann Prochaska : Product Owner 
- Anton Xu : Développeur 
- Louis Yvelin : Développeur 

=== Livrables

[cols="1,2"]
|===

| Base de données
| link:Documentation/Doc_tech_BD.pdf[Doc technique] +
  link:Documentation/Conception_BD.pdf[Conception] +
script de creation +
script d'insertion

| Web
| link:Documentation/Doc_util_PHP.pdf[Doc utilisateur] +
  link:Documentation/Doc_tech_PHP.pdf[Doc technique] +
  link:Documentation/SEP_PHP.pdf[Schéma d'enchaînement des pages] +
  link:Documentation/Cahier_recette.adoc[Cahier de recette]

| Python
| Doc technique

| Java
| Doc technique

| Gestion
| [Sprint backlog] +
  link:Comptes_rendus/Analyse_impact.pdf[Analyse d'impact]

|===

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

== Réalisations 

Nous avons trié les compétences par dossier : 

- Le dossier _php_ contient toutes les pages HTML/PHP, la page CSS ainsi que les images incluses.
- Le dossier _iot_ contient l'application Java ainsi que le script Python de récupération des données des capteurs.
- Le dossier _Documentation_ contient les diverses documentations du projet.
- Le dossier _bd_ contient les fichiers en relation avec la base de données avec diagramme de classes, dico des données et schéma relationnel ainsi que le script de création de la base de données.
- Le dossier _Comptes-rendus_ contient la copie des fichiers ou CR rendus sur moodle (sert de sauvegarde).

== Organisation et mode de fonctionnement

Chaque début de semaine nous allons tous faire un _git clone_ sur nos PC de la branche principale (master). Nous avons une branche pour chacune des compétences et chacun devra push son travail sur la branche avec la compétence il a travaillé tout au long de la semaine.
A la fin de la semaine au moment des rendus nous regardons les conflits entre la branche _master_ et les autres branches. Suite à ça nous faisons une merge request puis nous assemblons le tout afin de créer la release de la semaine. 

== Rendus hebdomadaire de Gestion de projet & Qualité

Après chaque sprint (semaine) une nouvelle version de notre application (release) sera disponible.
Nous utiliserons pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

Nous mettrons à jour le `README.adoc` avec les informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-9/releases/tag/v6_bis
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test : https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-9/blob/master/Documentation/cahier_recette.adoc
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application
