@startuml
class Produit{
    idProduit
    nomProduit
    descProduit
    prixProduit
    dateProduit
    stockProduit
    reduction
    imageProduit
}
class Categorie{
    idCat
    nomCat
    descCat
}
class SousCategorie{
    idSousCat
    nomSousCat
    descSousCat
}
class DetailCommande{
    quantite    
}
class Commande{
    idCommande
    montant
    tauxTVA
}
class User{
    idUser
    emailUser
    mdpUser
    adminUser
    nomUser
    prenomUser
    telUser
}
class Adresse{
    idAdresse
    surnomAdresse
    adresse
    complement
    ville
    codePostal
}
class CarteBancaire{
    idCB
    numeroCB
    nomCB
    dateCB
    cryptoCB
}
class Panier {
    quantite
}

Produit "0..*" - "1" SousCategorie : Appartenir
SousCategorie "0..*" - "1" Categorie : Faire partie de
Produit "1..*" -- "0..*" Commande
(Commande, Produit) .. DetailCommande

User "1" - "0..*" Commande : Passer
Adresse "1" - "0..*" Commande : Livrer
CarteBancaire "1" -- "0..*" Commande : Payer

User "1" -- "0..*" Adresse : Posséder
User "1" - "0..*" CarteBancaire  : Enregistrer

Produit "0..*" -- "0..*" User
(User, Produit) .. Panier




hide empty methods
hide circle
@enduml