@startuml
class Produit{
    idProduit
    nomProduit
    descProduit
    prixProduit
    imageProduit
    stockProduit
}
class Categorie{
    idCat
    nomCat
    descCat
}
class SousCategorie{
    idSousCat
    nomSousCat
    descSousCat
}
class DetailCommande{
    quantite    
}
class Commande{
    idCommande
    montant
    tauxTVA
}
class Client{
    idClient
    nomClient
    prenomClient
    emailClient
    telClient
}
class Adresse{
    idAdresse
    surnomAdresse
    adresse
    complement
    ville
    codePostal
}
class CarteBancaire{
    idCB
    numeroCB
    nomCB
    dateCB
    cryptoCB
}

Produit "0..*" - "1" SousCategorie : Appartenir
SousCategorie "0..*" - "1" Categorie : Faire partie de
Commande "0..*" -- "1..*" Produit
(Commande, Produit) .. DetailCommande
Commande "0..*" -- "1" Client : Passer
Client "1" - "0..*" Adresse : Posséder
CarteBancaire "0..*" - "1" Client : Enregistrer
Commande "0..*" -- "1" CarteBancaire : Payer
Commande "0..*" - "1" Adresse : Livrer

hide empty methods
hide circle
@enduml