@startuml
class Produit{
    idProduit
    nomProduit
    descProduit
    prixProduit
    dateProduit
    stockProduit
    reduction
    imageProduit
}
class Categorie{
    idCat
    nomCat
    descCat
}
class SousCategorie{
    idSousCat
    nomSousCat
    descSousCat
}
class DetailCommande{
    quantite    
}
class Commande{
    idCommande
    montant
    tauxTVA
}
class User{
    idUser
    emailUser
    mdpUser
    adminUser
    nomUser
    prenomUser
    telUser
}
class Adresse{
    idAdresse
    surnomAdresse
    adresse
    complement
    ville
    codePostal
}
class CarteBancaire{
    idCB
    numeroCB
    nomCB
    dateCB
    cryptoCB
}
class Panier {
    idPanier
}
class DetailPanier {
    quantite
}

Produit "0..*" - "1" SousCategorie : Appartenir
SousCategorie "0..*" - "1" Categorie : Faire partie de
Commande "0..*" -- "1..*" Produit
(Commande, Produit) .. DetailCommande

Commande "0..*" -- "1" User : Passer
Commande "0..*" -- "1" CarteBancaire : Payer
Commande "0..*" -- "1" Adresse : Livrer

User "1" -- "0..*" Adresse : Posséder
User "1" -- "0..*" CarteBancaire  : Enregistrer

User -- Panier
(Panier, Produit) .. DetailPanier




hide empty methods
hide circle
@enduml